version: '2.1'

services:
  mongo:
    image: mongo:3.6.1
    ports:
      - 27017:27017
    command: "--smallfiles --setParameter failIndexKeyTooLong=false"

networks:
  default:
    external:
      name: development
